apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: mailing-list-analysis-toolkit
  name: mailing-list-analysis-toolkit
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    workflowTemplateRef:
      name: mailing-list-analysis-toolkit
