kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: mailing-list-analysis-toolkit
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/aicoe/mailing-list-analysis-toolkit
      importPolicy:
        scheduled: true
