apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: fedora-mailing-list-analysis
  app.kubernetes.io/component: mailing-list-analysis-toolkit
  app.kubernetes.io/part-of: aiops-analytics
  app.kubernetes.io/managed-by: aicoe-aiops-devops-argocd

resources:
  - cronwf.yaml
  - imagestream.yaml
  - postsync-wf.yaml
  - wftmpl.yaml

generators:
  - secret-generator.yaml

patchesJson6902:
  - patch: &patch |
      - op: remove
        path: /metadata/name
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Workflow
      name: ignored
