apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ignored
  generateName: mailing-list-analysis-toolkit
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  workflowTemplateRef:
    name: mailing-list-analysis-toolkit
